"""added game table

Revision ID: 001
Revises: 
Create Date: 2021-06-26 21:27:33.759379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('game', sa.Text(), nullable=False),
        sa.Column('slug', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_data',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('game', sa.Text(), nullable=False),
        sa.Column('game_id', sa.BigInteger(), nullable=False),
        sa.Column('month', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('hours_watched', sa.BigInteger(), nullable=True),
        sa.Column('hours_streamed', sa.BigInteger(), nullable=True),
        sa.Column('peak_viewers', sa.BigInteger(), nullable=True),
        sa.Column('peak_channels', sa.BigInteger(), nullable=True),
        sa.Column('streamers', sa.BigInteger(), nullable=True),
        sa.Column('avg_viewers', sa.BigInteger(), nullable=True),
        sa.Column('avg_channels', sa.BigInteger(), nullable=True),
        sa.Column('avg_viewer_ratio', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_data')
    op.drop_table('game')
    # ### end Alembic commands ###
