"""added android app model

Revision ID: 003
Revises: 002
Create Date: 2021-08-29 14:58:19.787604

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('android_app',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('rank', sa.Integer(), nullable=False),
                    sa.Column('title', sa.Text(), nullable=False),
                    sa.Column('total_ratings', sa.BigInteger(), nullable=True),
                    sa.Column('installs', sa.Float(), nullable=True),
                    sa.Column('avg_rating', sa.BigInteger(), nullable=True),
                    sa.Column('growth_30day', sa.Float(), nullable=True),
                    sa.Column('growth_60day', sa.Float(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('category', sa.String(length=255), nullable=True),
                    sa.Column('rating_5', sa.BigInteger(), nullable=True),
                    sa.Column('rating_4', sa.BigInteger(), nullable=True),
                    sa.Column('rating_3', sa.BigInteger(), nullable=True),
                    sa.Column('rating_2', sa.BigInteger(), nullable=True),
                    sa.Column('rating_1', sa.BigInteger(), nullable=True),
                    sa.Column('paid', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('android_app')
    # ### end Alembic commands ###
