"""added crypto tables

Revision ID: 004
Revises: 003
Create Date: 2021-09-25 17:51:24.687163

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('symbol', sa.String(length=50), nullable=False),
                    sa.Column('slug', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crypto_price_history',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('crypto_id', sa.BigInteger(), nullable=False),
                    sa.Column('rank', sa.BigInteger(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('market_cap', sa.Float(), nullable=False),
                    sa.Column('total_volume', sa.Float(), nullable=False),
                    sa.Column('price_change_24h', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('market_cap_change', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('supply', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('ath', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('atl', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_price_history')
    op.drop_table('crypto')
    # ### end Alembic commands ###
