"""added created at column in crypto tables

Revision ID: 005
Revises: 004
Create Date: 2021-09-25 20:45:55.110748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto', sa.Column('created_at', sa.BigInteger(), nullable=False))
    op.add_column('crypto_price_history', sa.Column('created_at', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_price_history', 'created_at')
    op.drop_column('crypto', 'created_at')
    # ### end Alembic commands ###
